CREATE SEQUENCE producenci_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE kategoria_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE kategorie_producenci_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE kontakty_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE adresy_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE klienci_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE zamowienie_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE produkty_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE zamowienie_produkty_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE pracownicy_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE egzemplarze_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE faktura_seq
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE pozycje_faktury_seq
	START WITH 1
	INCREMENT BY 1;

COMMIT;