DROP TABLE temp_pracownicy CASCADE CONSTRAINTS;

DROP TABLE pozycje_faktury CASCADE CONSTRAINTS;

DROP TABLE faktura CASCADE CONSTRAINTS;

DROP TABLE egzemplarze CASCADE CONSTRAINTS;

DROP TABLE pracownicy CASCADE CONSTRAINTS;

DROP TABLE zamowienie_produkty CASCADE CONSTRAINTS;

DROP TABLE produkty CASCADE CONSTRAINTS;

DROP TABLE zamowienie CASCADE CONSTRAINTS;

DROP TABLE klienci CASCADE CONSTRAINTS;

DROP TABLE adresy CASCADE CONSTRAINTS;

DROP TABLE kontakty CASCADE CONSTRAINTS;

DROP TABLE kategorie_producenci CASCADE CONSTRAINTS;

DROP TABLE kategoria CASCADE CONSTRAINTS;

DROP TABLE producenci CASCADE CONSTRAINTS;

COMMIT ;