$CLS
PROMPT Menu DROP:
PROMPT
PROMPT 1. TABLE;
PROMPT
PROMPT 2. SEQUENCES;
PROMPT
PROMPT 3. VIEWS;
PROMPT
PROMPT 4. PACKAGE;
PROMPT
PROMPT 5. TRIGGERS;
PROMPT
ACCEPT wybor CHAR FORMAT 'A1' DEFAULT '0' PROMPT 'WYBIERZ NR OPCJI OD 1 DO 5: '
$CLS
DEFINE CURR_DIR='&1'
PROMPT wybor = &wybor
@'&CURR_DIR/&wybor.sql'
PROMPT # Wcisnij ENTER #
PAUSE
@main.sql